### ISSUE TITLE
[Question] How to find current file name?

### ISSUE THREAD

**Issue by shivajivarma** [mourner/tinyjam#8]
Is there any variable, where I can know current filename?

On template conditionally parsing some content based on page, currently I'm defining variable on each page to identify it. But want to know if there is alternative way to identity the file.

**Comment by mourner** [comment]
Hmm, not at the moment looking at the code, but that's a good point! We should add this. 

https://github.com/mourner/tinyjam/blob/78818d0e4bb8ec681bf21cb4f031d13510c840aa/index.js#L105-L107
